import { UserRole } from '@/types/auth';
import type { AdminUser } from '../types/adminUser';

export function createSeedAdminUsers(): AdminUser[] {
  return [
    {
      id: 'admin-1',
      email: 'admin@example.com',
      firstName: 'Jordan',
      lastName: 'Admin',
      role: UserRole.ADMIN,
      active: true,
      emailVerified: true,
      title: 'MS',
      phone: '+1 555 0199',
      dateOfBirth: '1985-09-01',
      nationality: 'GB',
      createdAt: '2025-01-10T09:00:00.000Z',
    },
    {
      id: 'admin-2',
      email: 'ops.lead@example.com',
      firstName: 'Sam',
      lastName: 'Chen',
      role: UserRole.ADMIN,
      active: true,
      emailVerified: true,
      title: 'MR',
      phone: '+65 8123 4567',
      dateOfBirth: '1988-03-22',
      nationality: 'SG',
      createdAt: '2025-03-01T11:30:00.000Z',
    },
    {
      id: 'user-1',
      email: 'user@example.com',
      firstName: 'Alex',
      lastName: 'Traveler',
      role: UserRole.USER,
      active: true,
      emailVerified: true,
      title: 'MR',
      phone: '+1 555 0100',
      dateOfBirth: '1990-04-12',
      nationality: 'US',
      createdAt: '2025-02-14T08:15:00.000Z',
    },
    {
      id: 'user-2',
      email: 'aisha.rahman@example.com',
      firstName: 'Aisha',
      lastName: 'Rahman',
      role: UserRole.USER,
      active: true,
      emailVerified: true,
      title: 'MS',
      phone: '+60 12-345 6789',
      dateOfBirth: '1993-07-18',
      nationality: 'MY',
      createdAt: '2025-06-20T14:00:00.000Z',
    },
    {
      id: 'user-3',
      email: 'ben.tan@example.com',
      firstName: 'Ben',
      lastName: 'Tan',
      role: UserRole.USER,
      active: false,
      emailVerified: true,
      title: 'MR',
      phone: '+65 9123 4567',
      dateOfBirth: '1991-11-05',
      nationality: 'SG',
      createdAt: '2025-07-02T10:45:00.000Z',
    },
    {
      id: 'user-4',
      email: 'chloe.ng@example.com',
      firstName: 'Chloe',
      lastName: 'Ng',
      role: UserRole.USER,
      active: true,
      emailVerified: false,
      title: 'MS',
      phone: '+60 19-876 5432',
      dateOfBirth: '1996-01-30',
      nationality: 'MY',
      createdAt: '2025-08-11T16:20:00.000Z',
    },
    {
      id: 'user-5',
      email: 'inactive.admin@example.com',
      firstName: 'Riley',
      lastName: 'Brooks',
      role: UserRole.ADMIN,
      active: false,
      emailVerified: true,
      title: 'MX',
      phone: '+44 7700 900123',
      dateOfBirth: '1982-12-09',
      nationality: 'GB',
      createdAt: '2024-11-03T07:00:00.000Z',
    },
  ];
}
