import type { Airport } from '../types';

/**
 * Seed airports for mock mode. Codes are IATA; coordinates are approximate.
 */
export const MOCK_AIRPORTS: readonly Airport[] = [
  {
    id: 'airport-kul',
    code: 'KUL',
    name: 'Kuala Lumpur International Airport',
    city: 'Kuala Lumpur',
    country: 'Malaysia',
    timezone: 'Asia/Kuala_Lumpur',
    terminalCount: 2,
    latitude: 2.7456,
    longitude: 101.7099,
    active: true,
  },
  {
    id: 'airport-sin',
    code: 'SIN',
    name: 'Singapore Changi Airport',
    city: 'Singapore',
    country: 'Singapore',
    timezone: 'Asia/Singapore',
    terminalCount: 4,
    latitude: 1.3644,
    longitude: 103.9915,
    active: true,
  },
  {
    id: 'airport-bkk',
    code: 'BKK',
    name: 'Suvarnabhumi Airport',
    city: 'Bangkok',
    country: 'Thailand',
    timezone: 'Asia/Bangkok',
    terminalCount: 1,
    latitude: 13.69,
    longitude: 100.7501,
    active: true,
  },
  {
    id: 'airport-cgk',
    code: 'CGK',
    name: 'Soekarno-Hatta International Airport',
    city: 'Jakarta',
    country: 'Indonesia',
    timezone: 'Asia/Jakarta',
    terminalCount: 3,
    latitude: -6.1256,
    longitude: 106.6559,
    active: true,
  },
  {
    id: 'airport-hkg',
    code: 'HKG',
    name: 'Hong Kong International Airport',
    city: 'Hong Kong',
    country: 'Hong Kong',
    timezone: 'Asia/Hong_Kong',
    terminalCount: 2,
    latitude: 22.308,
    longitude: 113.9185,
    active: true,
  },
  {
    id: 'airport-nrt',
    code: 'NRT',
    name: 'Narita International Airport',
    city: 'Tokyo',
    country: 'Japan',
    timezone: 'Asia/Tokyo',
    terminalCount: 3,
    latitude: 35.772,
    longitude: 140.3929,
    active: true,
  },
  {
    id: 'airport-hnd',
    code: 'HND',
    name: 'Haneda Airport',
    city: 'Tokyo',
    country: 'Japan',
    timezone: 'Asia/Tokyo',
    terminalCount: 3,
    latitude: 35.5494,
    longitude: 139.7798,
    active: true,
  },
  {
    id: 'airport-icn',
    code: 'ICN',
    name: 'Incheon International Airport',
    city: 'Seoul',
    country: 'South Korea',
    timezone: 'Asia/Seoul',
    terminalCount: 2,
    latitude: 37.4602,
    longitude: 126.4407,
    active: true,
  },
  {
    id: 'airport-dxb',
    code: 'DXB',
    name: 'Dubai International Airport',
    city: 'Dubai',
    country: 'United Arab Emirates',
    timezone: 'Asia/Dubai',
    terminalCount: 3,
    latitude: 25.2532,
    longitude: 55.3657,
    active: true,
  },
  {
    id: 'airport-lhr',
    code: 'LHR',
    name: 'London Heathrow Airport',
    city: 'London',
    country: 'United Kingdom',
    timezone: 'Europe/London',
    terminalCount: 5,
    latitude: 51.47,
    longitude: -0.4543,
    active: true,
  },
  {
    id: 'airport-cdg',
    code: 'CDG',
    name: 'Paris Charles de Gaulle Airport',
    city: 'Paris',
    country: 'France',
    timezone: 'Europe/Paris',
    terminalCount: 3,
    latitude: 49.0097,
    longitude: 2.5479,
    active: true,
  },
  {
    id: 'airport-fra',
    code: 'FRA',
    name: 'Frankfurt Airport',
    city: 'Frankfurt',
    country: 'Germany',
    timezone: 'Europe/Berlin',
    terminalCount: 2,
    latitude: 50.0379,
    longitude: 8.5622,
    active: true,
  },
  {
    id: 'airport-jfk',
    code: 'JFK',
    name: 'John F. Kennedy International Airport',
    city: 'New York',
    country: 'United States',
    timezone: 'America/New_York',
    terminalCount: 6,
    latitude: 40.6413,
    longitude: -73.7781,
    active: true,
  },
  {
    id: 'airport-lax',
    code: 'LAX',
    name: 'Los Angeles International Airport',
    city: 'Los Angeles',
    country: 'United States',
    timezone: 'America/Los_Angeles',
    terminalCount: 9,
    latitude: 33.9425,
    longitude: -118.4081,
    active: true,
  },
  {
    id: 'airport-syd',
    code: 'SYD',
    name: 'Sydney Kingsford Smith Airport',
    city: 'Sydney',
    country: 'Australia',
    timezone: 'Australia/Sydney',
    terminalCount: 3,
    latitude: -33.9399,
    longitude: 151.1753,
    active: true,
  },
  {
    id: 'airport-mel',
    code: 'MEL',
    name: 'Melbourne Airport',
    city: 'Melbourne',
    country: 'Australia',
    timezone: 'Australia/Melbourne',
    terminalCount: 4,
    latitude: -37.669,
    longitude: 144.841,
    active: true,
  },
  {
    id: 'airport-del',
    code: 'DEL',
    name: 'Indira Gandhi International Airport',
    city: 'New Delhi',
    country: 'India',
    timezone: 'Asia/Kolkata',
    terminalCount: 3,
    latitude: 28.5562,
    longitude: 77.1001,
    active: true,
  },
  {
    id: 'airport-bom',
    code: 'BOM',
    name: 'Chhatrapati Shivaji Maharaj International Airport',
    city: 'Mumbai',
    country: 'India',
    timezone: 'Asia/Kolkata',
    terminalCount: 2,
    latitude: 19.0896,
    longitude: 72.8656,
    active: true,
  },
  {
    id: 'airport-ist',
    code: 'IST',
    name: 'Istanbul Airport',
    city: 'Istanbul',
    country: 'Türkiye',
    timezone: 'Europe/Istanbul',
    terminalCount: 1,
    latitude: 41.2753,
    longitude: 28.7519,
    active: true,
  },
  {
    id: 'airport-pen',
    code: 'PEN',
    name: 'Penang International Airport',
    city: 'George Town',
    country: 'Malaysia',
    timezone: 'Asia/Kuala_Lumpur',
    terminalCount: 1,
    latitude: 5.2971,
    longitude: 100.2769,
    active: true,
  },
  {
    id: 'airport-szb',
    code: 'SZB',
    name: 'Sultan Abdul Aziz Shah Airport',
    city: 'Subang',
    country: 'Malaysia',
    timezone: 'Asia/Kuala_Lumpur',
    terminalCount: 1,
    latitude: 3.1306,
    longitude: 101.5492,
    active: false,
  },
] as const;
