import type { AdminFlight } from '../types/adminFlight';

export function createSeedAdminFlights(): AdminFlight[] {
  const now = new Date().toISOString();

  return [
    {
      id: 'adm-flight-1',
      airline: 'MH',
      flightNumber: 'MH1',
      origin: 'KUL',
      destination: 'NRT',
      aircraft: 'A350',
      departure: '2026-10-20T09:15',
      arrival: '2026-10-20T17:05',
      terminal: 'T1',
      gate: 'C12',
      status: 'SCHEDULED',
      availableSeats: 86,
      fareClasses: ['ECONOMY', 'BUSINESS', 'FIRST'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'adm-flight-2',
      airline: 'SQ',
      flightNumber: 'SQ118',
      origin: 'SIN',
      destination: 'KUL',
      aircraft: 'A321',
      departure: '2026-10-20T11:40',
      arrival: '2026-10-20T12:45',
      terminal: 'T3',
      gate: 'B7',
      status: 'BOARDING',
      availableSeats: 24,
      fareClasses: ['ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'adm-flight-3',
      airline: 'AK',
      flightNumber: 'AK512',
      origin: 'KUL',
      destination: 'BKK',
      aircraft: 'A320',
      departure: '2026-10-21T07:05',
      arrival: '2026-10-21T08:10',
      terminal: 'T2',
      gate: 'A3',
      status: 'DELAYED',
      availableSeats: 41,
      fareClasses: ['ECONOMY'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'adm-flight-4',
      airline: 'CX',
      flightNumber: 'CX720',
      origin: 'HKG',
      destination: 'SIN',
      aircraft: 'B777',
      departure: '2026-10-19T14:20',
      arrival: '2026-10-19T18:05',
      terminal: 'T1',
      gate: 'D22',
      status: 'DEPARTED',
      availableSeats: 12,
      fareClasses: ['ECONOMY', 'BUSINESS', 'FIRST'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'adm-flight-5',
      airline: 'TG',
      flightNumber: 'TG408',
      origin: 'BKK',
      destination: 'KUL',
      aircraft: 'B787',
      departure: '2026-10-18T16:30',
      arrival: '2026-10-18T19:40',
      terminal: 'T1',
      gate: 'E4',
      status: 'ARRIVED',
      availableSeats: 0,
      fareClasses: ['ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'adm-flight-6',
      airline: 'JL',
      flightNumber: 'JL723',
      origin: 'NRT',
      destination: 'SIN',
      aircraft: 'B787',
      departure: '2026-10-22T22:10',
      arrival: '2026-10-23T05:20',
      terminal: 'T2',
      gate: 'F18',
      status: 'SCHEDULED',
      availableSeats: 63,
      fareClasses: ['ECONOMY', 'BUSINESS', 'FIRST'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'adm-flight-7',
      airline: 'MH',
      flightNumber: 'MH613',
      origin: 'KUL',
      destination: 'SIN',
      aircraft: 'B737',
      departure: '2026-10-17T08:00',
      arrival: '2026-10-17T09:05',
      terminal: 'T1',
      gate: 'A9',
      status: 'CANCELLED',
      availableSeats: 150,
      fareClasses: ['ECONOMY', 'BUSINESS'],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'adm-flight-8',
      airline: 'KE',
      flightNumber: 'KE671',
      origin: 'ICN',
      destination: 'KUL',
      aircraft: 'A330',
      departure: '2026-10-23T13:45',
      arrival: '2026-10-23T19:15',
      terminal: 'T1',
      gate: 'G11',
      status: 'SCHEDULED',
      availableSeats: 97,
      fareClasses: ['ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS', 'FIRST'],
      createdAt: now,
      updatedAt: now,
    },
  ];
}
